version: '3.3'

services:
  web:
    image: nginx:latest
    ports:
      - '8090:80'
    volumes:
      - ./src/web:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./src/web:/var/www/html
