version: '3.3'

services:

  web:
    image: nginx:latest
    container_name: nginx_repo_1-
    ports:
      - '8090:80'
    volumes:
      - ./src/vendor/PHP/learning_php/POS_GET_PHP:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    image: php:8-fpm
    container_name: php-fpm_repo_1-
    volumes:
      - ./src/vendor/PHP/learning_php/POS_GET_PHP:/var/www/html
  
  mysql: 
    image: mysql:8.0
    container_name: mysql-repo_1-
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: repo_1-db
      MYSQL_USER: repo_1-user
      MYSQL_PASSWORD: repo_1-pass
    ports:
      - "3308:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-repo_1-
    environment:
      PMA_HOST: mysql
      PMA_USER: repo_1-user
      PMA_PASSWORD: repo_1-pass
    ports:
      - "8091:80"
    depends_on:
      - mysql
